/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Docs": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "WebApp": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}
